export{version} from './build/version';
import utilDataRange from './src/utils/data-range/DataRange';
import ToolTip from './src/utils/tooltip/ToolTip';
import util from './src/tool/util';
import coordOption from './src/utils/coord/DefaultOptions';
console.log(coordOption);
var newObj=util.clone({a:1});
utilDataRange.drawDataRange();
var tooltipCfg={position: [5, 5],style:'position:absolute;background-Color:rgba(0,0,0,0.7);transition:top 0.2s,left 0.2s;border-radius: 2px;color:#fff;line-height: 16px;padding:5px 10px;'};
var toolTip=new ToolTip(document.getElementById('davz-chart'),tooltipCfg);
toolTip.moveTo(15,0);
toolTip.setContent('消息提示框');
toolTip.show();
toolTip.hideLater(600);
